name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  AQUA_USER: ${{ secrets.AQUA_USER }} # Aqua Registry
  AQUA_PASSWORD: ${{ secrets.AQUA_PASSWORD }} # Aqua Registry
  AQUA_TOKEN: ${{ secrets.AQUA_TOKEN }} # Aqua Scanner authentication
  AQUA_HOST: ${{ secrets.AQUA_HOST }} # Aqua Scanner authentication
  BUILD_NUMBER: ${{ github.run_id }}
  BUILD_NAME: ${{ github.repository }}
  GITHUB_WORKSPACE: ${{ github.workspace }}
  
jobs:     
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  
    - name: List Docker images
      run: |
        docker image ls 
    - name: Aqua Image Scanner
      run: |
        docker image ls 
        docker login registry.aquasec.com -u $AQUA_USER -p $AQUA_PASSWORD
        docker pull registry.aquasec.com/scanner:2405.20.1
        docker run --rm -v $GITHUB_WORKSPACE:/tmp -v /var/run/docker.sock:/var/run/docker.sock -e SCALOCK_LOG_LEVEL=debug -e BUILD_NUMBER=$BUILD_NUMBER -e BUILD_JOB_NAME=$BUILD_NAME registry.aquasec.com/scanner:2405.20.1 scan -w /tmp --host $AQUA_HOST --token $AQUA_TOKEN --show-negligible --registry "Docker Hub" stanhoe/spring4shell:demo --htmlfile /tmp/out.html --jsonfile /tmp/out.json > /dev/null
        docker image ls
    - name: List Docker images
      run: |
        docker image ls 
    - uses: actions/upload-artifact@v3
      with:
        name: aqua-artifact
        path: out.*
